# Generated by Django 5.2.8 on 2025-11-18 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, unique=True, verbose_name='Avto_Nomer')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Mashina iyesi')),
                ('rfid_tag', models.CharField(max_length=100, unique=True, verbose_name='RFID-tag')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kiriw waqti')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Shigiw waqti')),
                ('is_inside', models.BooleanField(default=True, verbose_name='Avtomobil parkovkada')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session', to='core.car', verbose_name='Avtomobil')),
            ],
        ),
    ]
