# Generated by Django 5.2.8 on 2025-11-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Гос. номер / Название')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='Владелец')),
                ('rfid_tag', models.CharField(max_length=50, unique=True, verbose_name='RFID метка (EPC)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_tag', models.CharField(max_length=50, verbose_name='Считанная метка')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время проезда')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Доступ разрешен')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Журнал въездов',
                'verbose_name_plural': 'Журнал въездов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
