# Generated by Django 5.2.8 on 2025-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Журнал проездов', 'verbose_name_plural': 'Журнал проездов'},
        ),
        migrations.AddField(
            model_name='car',
            name='is_inside',
            field=models.BooleanField(default=False, verbose_name='На территории'),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='action',
            field=models.CharField(choices=[('IN', 'Вход (Kirish)'), ('OUT', 'Выход (Chiqish)'), ('DENIED', 'Отказано (Rad etildi)')], default='DENIED', max_length=10, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
