# Generated by Django 5.2.8 on 2026-01-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entrylog_options_car_is_inside_entrylog_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Avtomobil', 'verbose_name_plural': 'Avtomobiller'},
        ),
        migrations.AlterModelOptions(
            name='entrylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Kirdi shiqti jurnali', 'verbose_name_plural': 'Kirdi shiqti jurnali'},
        ),
        migrations.AddField(
            model_name='car',
            name='last_entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Songi kiriw waqti'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opisanie'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_inside',
            field=models.BooleanField(default=False, verbose_name='Avtoparkte'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Iyesi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rfid_tag',
            field=models.CharField(max_length=50, unique=True, verbose_name='RFID metka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Avtomobil nomeri'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='action',
            field=models.CharField(choices=[('IN', 'Вход (Kiriw)'), ('OUT', 'Выход (Shigiw)'), ('DENIED', 'Отказано (Inkar etildi)')], default='DENIED', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car', verbose_name='Avtomobil'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Ruxsat berilgen'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='rfid_tag',
            field=models.CharField(max_length=50, verbose_name='Oqilgan teg'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waqit'),
        ),
    ]
