# Generated by Django 5.2.8 on 2026-01-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_car_options_alter_entrylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylog',
            name='stay_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turǵan waqtı'),
        ),
    ]
