# Generated by Django 6.0.4 on 2026-05-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entrylog_stay_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['title'], 'verbose_name': 'Avtomobil', 'verbose_name_plural': 'Avtomobiller'},
        ),
        migrations.AlterModelOptions(
            name='entrylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Kirdi-shıqtı jurnalı', 'verbose_name_plural': 'Kirdi-shıqtı jurnalı'},
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Reńi'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Aktiv emes kartalar uchın kiriw inkar etiledi.', verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='car',
            name='last_exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sońǵı shıǵıw waqtı'),
        ),
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Iye telefonı'),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Jeńil avtomobil'), ('TRUCK', 'Júk avtomobili'), ('BUS', 'Avtobus'), ('MOTO', 'Mototsikl'), ('VAN', 'Mikroavtobus'), ('OTHER', 'Basqa')], default='SEDAN', max_length=10, verbose_name='Avtomobil túri'),
        ),
        migrations.AddField(
            model_name='entrylog',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eskerme'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Qosımsha maǵlıwmat'),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_entry_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sońǵı kiriw waqtı'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='action',
            field=models.CharField(choices=[('IN', 'Kiriw'), ('OUT', 'Shıǵıw'), ('DENIED', 'Inkar etildi'), ('COOLDOWN', 'Júdá tez (cooldown)')], default='DENIED', max_length=10, verbose_name='Háleket'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.car', verbose_name='Avtomobil'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Ruxsat berildi'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='rfid_tag',
            field=models.CharField(max_length=50, verbose_name='Oqılǵan teg'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='stay_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Túrǵan waqtı'),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waqıt'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['rfid_tag'], name='core_car_rfid_ta_1202e1_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_inside', 'is_active'], name='core_car_is_insi_5b7de9_idx'),
        ),
        migrations.AddIndex(
            model_name='entrylog',
            index=models.Index(fields=['-timestamp'], name='core_entryl_timesta_cfd7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='entrylog',
            index=models.Index(fields=['action', '-timestamp'], name='core_entryl_action_8a6a0b_idx'),
        ),
    ]
